config/routes.rb
require 'api_constraints'
require 'subdomain_constraints'

Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'user/registrations' }
  devise_for(
    :admins, path: ENV.fetch('ADMIN_PATH',
                             '/'), controllers: { registrations: 'admin/registrations' }
  )

  constraints(SubdomainConstraints.new(subdomain: ENV.fetch('ADMIN_SUBDOMAIN', nil))) do
    namespace :admin, path: ENV.fetch('ADMIN_PATH', nil) do
      root to: 'dashboard#index', as: :dashboard

      resources :locations, except: :show do
        resources :services, except: %i[show index] do
          resources :contacts, except: %i[show index], controller: 'service_contacts'
        end
        resources :contacts, except: %i[show index]
      end

      resources :organizations, except: :show do
        resources :contacts, except: %i[show index], controller: 'organization_contacts'
      end
      resources :programs, except: :show
      resources :services, only: :index

      namespace :csv, defaults: { format: 'csv' } do
        get 'addresses'
        get 'contacts'
        get 'holiday_schedules'
        get 'locations'
        get 'mail_addresses'
        get 'organizations'
        get 'phones'
        get 'programs'
        get 'regular_schedules'
        get 'services'
      end

      get 'locations/:location_id/services/:id', to: 'services#edit'
      get 'locations/:location_id/services/:service_id/contacts/:id', to: 'service_contacts#edit'
      get 'locations/:location_id/contacts/:id', to: 'contacts#edit'
      get 'locations/:id', to: 'locations#edit'
      get 'organizations/:id', to: 'organizations#edit'
      get 'organizations/:organization_id/contacts/:id', to: 'organization_contacts#edit'
      get 'programs/:id', to: 'programs#edit'
    end
  end

  resources :api_applications, except: :show
  get 'api_applications/:id' => 'api_applications#edit'

  constraints(SubdomainConstraints.new(subdomain: ENV.fetch('API_SUBDOMAIN', nil))) do
    namespace :api, path: ENV.fetch('API_PATH', nil), defaults: { format: 'json' } do
      scope module: :v1, constraints: ApiConstraints.new(version: 1) do
        get '/' => 'root#index'
        get '.well-known/status' => 'status#check_status'

        resources :organizations do
          resources :locations, only: :create
        end
        get 'organizations/:organization_id/locations',
            to: 'organizations#locations', as: :org_locations

        resources :locations do
          resources :address, except: %i[index show]
          resources :mail_address, except: %i[index show]
          resources :contacts, except: [:show] do
            resources :phones,
                      except: %i[show index],
                      path: '/phones', controller: 'contact_phones'
          end
          resources :phones, except: [:show], path: '/phones', controller: 'location_phones'
          resources :services
        end

        resources :search, only: :index

        resources :categories, only: :index

        put 'services/:service_id/categories',
            to: 'services#update_categories', as: :service_categories
        get 'categories/:taxonomy_id/children', to: 'categories#children', as: :category_children
        get 'locations/:location_id/nearby', to: 'search#nearby', as: :location_nearby

        match '*unmatched_route' => 'errors#raise_not_found!',
              via: %i[get delete patch post put]

        match '*unmatched_route' => 'cors#render_204', via: [:options]
      end
    end
  end

  root to: 'home#index'
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :organization, optional: false

  has_one :address, dependent: :destroy
  accepts_nested_attributes_for :address, allow_destroy: true

  has_many :contacts, dependent: :destroy

  has_one :mail_address, dependent: :destroy, inverse_of: :location
  accepts_nested_attributes_for :mail_address, allow_destroy: true

  has_many :phones, dependent: :destroy, inverse_of: :location
  accepts_nested_attributes_for :phones,
                                allow_destroy: true, reject_if: :all_blank

  has_many :services, dependent: :destroy

  has_many :regular_schedules, dependent: :destroy, inverse_of: :location
  accepts_nested_attributes_for :regular_schedules,
                                allow_destroy: true, reject_if: :all_blank

  has_many :holiday_schedules, dependent: :destroy, inverse_of: :location
  accepts_nested_attributes_for :holiday_schedules,
                                allow_destroy: true, reject_if: :all_blank

  validates :address,
            presence: { message: I18n.t('errors.messages.no_address') },
            unless: :virtual?

  validates :description, :name,
            presence: { message: I18n.t('errors.messages.blank_for_location') }

  ## Uncomment the line below if you want to require a short description.
  ## We recommend having a short description so that web clients can display
  ## an overview within the search results. See smc-connect.org as an example.
  # validates :short_desc, presence: { message: I18n.t('errors.messages.blank_for_location') }

  ## Uncomment the line below if you want to limit the
  ## short description's length. If you want to display a short description
  ## on a front-end client like smc-connect.org, we recommmend writing or
  ## re-writing a description that's one to two sentences long, with a
  ## maximum of 200 characters. This is just a recommendation though.
  ## Feel free to modify the maximum below, and the way the description is
  ## displayed in the ohana-web-search client to suit your needs.
  # validates :short_desc, length: { maximum: 200 }

  validates :website, url: true, allow_blank: true

  validates :languages, pg_array: true

  validates :admin_emails, array: { email: true }

  validates :email, email: true, allow_blank: true

  after_validation :geocode, if: :needs_geocoding?
  after_validation :downcase_admin_emails
  after_validation :remove_duplicates

  geocoded_by :full_physical_address

  extend Enumerize
  serialize :accessibility, Array
  # Don't change the terms here! You can change their display
  # name in config/locales/en.yml
  enumerize :accessibility,
            in: %i[cd deaf_interpreter disabled_parking elevator ramp
                   restroom tape_braille tty wheelchair wheelchair_van],
            multiple: true

  auto_strip_attributes :description, :email, :name, :short_desc,
                        :transportation, :website

  auto_strip_attributes :admin_emails, reject_blank: true, nullify: true, nullify_array: false

  extend FriendlyId
  friendly_id :slug_candidates, use: [:history]

  # Try building a slug based on the following fields in
  # increasing order of specificity.
  def slug_candidates
    [
      :name,
      %i[name address_street],
      %i[name mail_address_city]
    ]
  end

  def address_street
    address.address_1 if address.present?
  end

  def mail_address_city
    mail_address.city if mail_address.present?
  end

  def full_physical_address
    return if address.blank?

    "#{address.address_1}, #{address.city}, #{address.state_province} #{address.postal_code}"
  end

  def needs_geocoding?
    return false if address.blank? || address.marked_for_destruction?
    return true if latitude.blank? && longitude.blank?

    address.changed? && !address.new_record?
  end

  def downcase_admin_emails
    admin_emails&.map!(&:downcase)
  end

  def remove_duplicates
    admin_emails&.uniq!
  end

  # See app/models/concerns/search.rb
  include Search
end

app/controllers/admin/locations_controller.rb
class Admin
  class LocationsController < ApplicationController
    before_action :authenticate_admin!
    layout 'admin'

    def index
      @locations = Kaminari.paginate_array(policy_scope(Location)).
                   page(params[:page]).per(params[:per_page])
    end

    def edit
      @location = Location.find(params[:id])
      @org = @location.organization

      authorize @location
    end

    def update
      @location = Location.find(params[:id])
      @org = @location.organization

      authorize @location

      if @location.update(location_params)
        redirect_to [:admin, @location],
                    notice: t('admin.notices.location_updated')
      else
        render :edit
      end
    end

    def new
      @location = Location.new
      authorize @location
    end

    def create
      @location = Location.new(location_params)
      org = @location.organization

      authorize org if org.present?

      if @location.save
        redirect_to [:admin, @location], notice: t('admin.notices.location_created')
      else
        render :new
      end
    end

    def destroy
      location = Location.find(params[:id])

      authorize location

      location.destroy
      redirect_to admin_locations_url
    end

    private

    # rubocop:disable Metrics/MethodLength
    def location_params
      params.require(:location).permit(
        :organization_id, { accessibility: [] }, :active, { admin_emails: [] },
        :alternate_name, :description, :email, { languages: [] }, :latitude,
        :longitude, :name, :short_desc, :transportation, :website, :virtual,
        address_attributes: %i[
          address_1 address_2 city state_province postal_code country id _destroy
        ],
        mail_address_attributes: %i[
          attention address_1 address_2 city state_province postal_code country id _destroy
        ],
        phones_attributes: %i[
          country_prefix department extension number number_type vanity_number id _destroy
        ],
        regular_schedules_attributes: %i[weekday opens_at closes_at id _destroy],
        holiday_schedules_attributes: %i[closed start_date end_date opens_at closes_at id _destroy]
      )
    end
    # rubocop:enable Metrics/MethodLength
  end
end

app/controllers/api/v1/locations_controller.rb
module Api
  module V1
    class LocationsController < ApplicationController
      include TokenValidator
      include PaginationHeaders
      include CustomErrors
      include Cacheable

      after_action :set_cache_control, only: %i[index show]

      def index
        locations = Location.includes(:organization, :address, :phones).
                    page(params[:page]).per(params[:per_page]).
                    order('created_at DESC')

        render json: locations, each_serializer: LocationsSerializer, status: :ok
        generate_pagination_headers(locations)
      end

      def show
        location = Location.includes(
          contacts: :phones,
          services: %i[categories contacts phones regular_schedules
                       holiday_schedules]
        ).find(params[:id])
        render json: location, status: :ok if stale?(location, public: true)
      end

      def update
        location = Location.find(params[:id])
        location.update!(location_params)
        render json: location, status: :ok
      end

      def create
        org = Organization.find(params[:organization_id])
        location = org.locations.create!(location_params)
        response_hash = {
          id: location.id,
          name: location.name,
          slug: location.slug
        }
        render json: response_hash, status: :created, location: [:api, location]
      end

      def destroy
        location = Location.find(params[:id])
        location.destroy
        head :no_content
      end

      private

      def location_params
        params.permit(
          { accessibility: [] }, :active, { admin_emails: [] }, :alternate_name, :description,
          :email, { languages: [] }, :latitude, :longitude, :name, :short_desc,
          :transportation, :website, :virtual,
          address_attributes: %i[
            address_1 address_2 city state_province postal_code
            country id _destroy
          ]
        )
      end
    end
  end
end

app/views/admin/locations/_confirm_delete_location.html.haml
.modal-dialog
  .modal-content
    .modal-header
      = button_tag(type: 'button', class: 'close', data: { dismiss: 'modal' }) do
        %span{ 'aria-hidden' => 'true' }
          &times;
        %span.sr-only
          Close
      %h4.modal-title#my-modal-label
        Are you ABSOLUTELY sure?
    .modal-body
      %p
        This action CANNOT be undone. This will delete
        %strong
          = loc_name
        and all of its associated services from
        %strong
          = org_name
        permanently.
    .modal-footer
      %button.btn.btn-default{ 'data-dismiss' => 'modal' } Close
      = link_to t('admin.buttons.confirm_delete_location'), { action: :destroy, id: location_id }, method: :delete, class: 'btn btn-danger'

app/views/admin/locations/_form.html.haml
= render 'admin/locations/forms/fields', f: f, location: location

.content-box
  %h2 Contacts
  - if location.contacts.present?
    Click a Contact below to view and update it:
    %p
    - location.contacts.each do |contact|
      = link_to contact.name, edit_admin_location_contact_path(location, contact)
      %br
  %p
    = link_to t('admin.buttons.add_contact'), new_admin_location_contact_path(location), class: 'btn btn-primary'

.content-box
  %h2 Services
  Click a Service below to view and update it:
  %p
  - location.services.each_with_index do |service, i|
    = link_to service.name || "Service ##{i + 1}", edit_admin_location_service_path(location, service)
    %br
  %p
    = link_to t('admin.buttons.add_service'), new_admin_location_service_path(location), class: 'btn btn-primary'

.danger-zone
  %header
    %strong
      Danger Zone
  %h4
    Delete this location
  %p
    Once you delete a location, there is no going back. Please be certain.
  %p
    = link_to t('admin.buttons.delete_location'), {}, href: '', data: { toggle: 'modal', target: '#modal-window' }, class: 'boxed-action'
.modal.fade#modal-window{ 'aria-hidden' => 'true', 'aria-labelledby' => 'my-modal-label', 'role' => 'dialog', 'tabindex' => '-1' }
  = render 'admin/locations/confirm_delete_location', location_id: location.id, loc_name: location.name, org_name: org.name

.save-box.navbar-default
  %p
    Editing
    %strong
      #{org.name} / #{location.name}
  = f.submit t('admin.buttons.save_changes'), class: 'btn btn-success', data: { disable_with: 'Please wait...' }

app/views/admin/locations/edit.html.haml
.content-box
  %h2= @location.name == @org.try(:name) ? @location.name : "#{@org.try(:name)} / #{@location.name}"
= form_for [:admin, @location], html: { class: 'edit-entry' } do |f|
  = render 'form', f: f, location: @location, org: @org

app/views/admin/locations/index.html.haml
%p
  Below you should see a list of locations that you are allowed to administer based on your email address.
  If there are any locations missing,
  please #{mail_to SETTINGS[:admin_support_email], 'let us know'}.
%p
  To start updating, click on one of the links, which will take you to the details page
  for the location.
- if current_admin.super_admin?
  %p As a super admin, you have access to all locations in the database. Please make updates responsibly.

%p
  - @locations.each do |location|
    %ul
      = link_to location.second, edit_admin_location_path(location.third)
  = paginate @locations

- if @locations.present?
  %p
    = link_to t('admin.buttons.add_location'), new_admin_location_path, class: 'btn btn-primary'

app/views/admin/locations/new.html.haml
.content-box
  %h1 Create a new location
  %p
    You'll be able to add Contacts and Services to this location after you create it.

= form_for [:admin, @location], url: admin_locations_path, html: { method: :post, class: 'edit-entry' } do |f|
  = render 'admin/locations/forms/new_location_form', f: f, location: @location