config/routes.rb
require 'api_constraints'
require 'subdomain_constraints'

Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'user/registrations' }
  devise_for(
    :admins, path: ENV.fetch('ADMIN_PATH',
                             '/'), controllers: { registrations: 'admin/registrations' }
  )

  constraints(SubdomainConstraints.new(subdomain: ENV.fetch('ADMIN_SUBDOMAIN', nil))) do
    namespace :admin, path: ENV.fetch('ADMIN_PATH', nil) do
      root to: 'dashboard#index', as: :dashboard

      resources :locations, except: :show do
        resources :services, except: %i[show index] do
          resources :contacts, except: %i[show index], controller: 'service_contacts'
        end
        resources :contacts, except: %i[show index]
      end

      resources :organizations, except: :show do
        resources :contacts, except: %i[show index], controller: 'organization_contacts'
      end
      resources :programs, except: :show
      resources :services, only: :index

      namespace :csv, defaults: { format: 'csv' } do
        get 'addresses'
        get 'contacts'
        get 'holiday_schedules'
        get 'locations'
        get 'mail_addresses'
        get 'organizations'
        get 'phones'
        get 'programs'
        get 'regular_schedules'
        get 'services'
      end

      get 'locations/:location_id/services/:id', to: 'services#edit'
      get 'locations/:location_id/services/:service_id/contacts/:id', to: 'service_contacts#edit'
      get 'locations/:location_id/contacts/:id', to: 'contacts#edit'
      get 'locations/:id', to: 'locations#edit'
      get 'organizations/:id', to: 'organizations#edit'
      get 'organizations/:organization_id/contacts/:id', to: 'organization_contacts#edit'
      get 'programs/:id', to: 'programs#edit'
    end
  end

  resources :api_applications, except: :show
  get 'api_applications/:id' => 'api_applications#edit'

  constraints(SubdomainConstraints.new(subdomain: ENV.fetch('API_SUBDOMAIN', nil))) do
    namespace :api, path: ENV.fetch('API_PATH', nil), defaults: { format: 'json' } do
      scope module: :v1, constraints: ApiConstraints.new(version: 1) do
        get '/' => 'root#index'
        get '.well-known/status' => 'status#check_status'

        resources :organizations do
          resources :locations, only: :create
        end
        get 'organizations/:organization_id/locations',
            to: 'organizations#locations', as: :org_locations

        resources :locations do
          resources :address, except: %i[index show]
          resources :mail_address, except: %i[index show]
          resources :contacts, except: [:show] do
            resources :phones,
                      except: %i[show index],
                      path: '/phones', controller: 'contact_phones'
          end
          resources :phones, except: [:show], path: '/phones', controller: 'location_phones'
          resources :services
        end

        resources :search, only: :index

        resources :categories, only: :index

        put 'services/:service_id/categories',
            to: 'services#update_categories', as: :service_categories
        get 'categories/:taxonomy_id/children', to: 'categories#children', as: :category_children
        get 'locations/:location_id/nearby', to: 'search#nearby', as: :location_nearby

        match '*unmatched_route' => 'errors#raise_not_found!',
              via: %i[get delete patch post put]

        match '*unmatched_route' => 'cors#render_204', via: [:options]
      end
    end
  end

  root to: 'home#index'
end

app/models/organization.rb
class Organization < ApplicationRecord
  default_scope { order('id DESC') }

  has_many :locations, dependent: :destroy
  has_many :programs, dependent: :destroy
  has_many :contacts, dependent: :destroy

  has_many :phones, dependent: :destroy, inverse_of: :organization
  accepts_nested_attributes_for :phones,
                                allow_destroy: true, reject_if: :all_blank

  validates :name,
            presence: { message: I18n.t('errors.messages.blank_for_org') },
            uniqueness: { case_sensitive: false }

  validates :description,
            presence: { message: I18n.t('errors.messages.blank_for_org') }

  validates :email, email: true, allow_blank: true
  validates :website, url: true, allow_blank: true
  validates :date_incorporated, date: true

  validates :accreditations, :funding_sources, :licenses, pg_array: true

  auto_strip_attributes :alternate_name, :description, :email, :legal_status,
                        :name, :tax_id, :tax_status, :website

  def self.with_locations(ids)
    joins(:locations).where(locations: { id: ids }).distinct
  end

  extend FriendlyId
  friendly_id :name, use: [:history]

  after_save :touch_locations, if: :needs_touch?

  private

  def needs_touch?
    return false if locations.count.zero?

    saved_change_to_name?
  end

  def touch_locations
    locations.find_each(&:touch)
  end
end

app/controllers/admin/organizations_controller.rb
class Admin
  class OrganizationsController < ApplicationController
    before_action :authenticate_admin!
    layout 'admin'

    include Taggable

    def index
      @all_orgs = policy_scope(Organization)
      @orgs = Kaminari.paginate_array(@all_orgs).page(params[:page])

      respond_to do |format|
        format.html
        format.json do
          render json: @all_orgs.select { |org| org[1] =~ /#{params[:q]}/i }
        end
      end
    end

    def edit
      @organization = Organization.find(params[:id])

      authorize @organization
    end

    def update
      @organization = Organization.find(params[:id])

      authorize @organization
      preprocess_organization_params

      if @organization.update(org_params)
        redirect_to [:admin, @organization],
                    notice: t('admin.notices.organization_updated')
      else
        render :edit
      end
    end

    def new
      @organization = Organization.new
      authorize @organization
    end

    def create
      preprocess_organization_params
      @organization = Organization.new(org_params)
      authorize @organization

      if @organization.save
        redirect_to admin_organizations_url,
                    notice: t('admin.notices.organization_created')
      else
        render :new
      end
    end

    def destroy
      organization = Organization.find(params[:id])
      authorize organization
      organization.destroy
      redirect_to admin_organizations_url
    end

    private

    def preprocess_organization_params
      shift_and_split_params(params[:organization], :accreditations, :licenses)
    end

    def org_params
      params.require(:organization).permit(
        { accreditations: [] }, :alternate_name, :date_incorporated, :description,
        :email, { funding_sources: [] }, :legal_status, { licenses: [] }, :name,
        :tax_id, :tax_status, :website,
        phones_attributes: %i[
          country_prefix department extension number number_type vanity_number id _destroy
        ]
      )
    end
  end
end

app/controllers/api/v1/organizations_controller.rb
module Api
  module V1
    class OrganizationsController < ApplicationController
      include TokenValidator
      include PaginationHeaders
      include CustomErrors

      def index
        orgs = Organization.includes(:contacts, :phones).
               page(params[:page]).per(params[:per_page])
        render json: orgs, status: :ok
        generate_pagination_headers(orgs)
      end

      def show
        org = Organization.find(params[:id])
        render json: org, status: :ok
      end

      def update
        org = Organization.find(params[:id])
        org.update!(org_params)
        render json: org, status: :ok
      end

      def create
        org = Organization.create!(org_params)
        render json: org, status: :created, location: [:api, org]
      end

      def destroy
        org = Organization.find(params[:id])
        org.destroy
        head :no_content
      end

      def locations
        org = Organization.find(params[:organization_id])
        locations = org.locations.includes(:address, :phones).
                    page(params[:page]).per(params[:per_page])
        render json: locations, each_serializer: LocationsSerializer, status: :ok
        generate_pagination_headers(locations)
      end

      private

      def org_params
        params.require(:organization).permit(
          { accreditations: [] }, :alternate_name, :date_incorporated, :description,
          :email, { funding_sources: [] }, :legal_status, { licenses: [] }, :name,
          :tax_id, :tax_status, :website
        )
      end
    end
  end
end

app/views/admin/organizations/_confirm_delete_organization.html.haml
.modal-dialog
  .modal-content
    .modal-header
      = button_tag(type: 'button', class: 'close', data: { dismiss: 'modal' }) do
        %span{ 'aria-hidden' => 'true' }
          &times;
        %span.sr-only
          Close
      %h4.modal-title#my-modal-label
        Are you ABSOLUTELY sure?
    .modal-body
      %p
        This action CANNOT be undone. This will delete
        %strong
          = org_name
        and all of its associated locations permanently.
    .modal-footer
      %button.btn.btn-default{ 'data-dismiss' => 'modal' } Close
      = link_to t('admin.buttons.confirm_delete_organization'), { action: :destroy, id: org_id }, method: :delete, class: 'btn btn-danger'

app/views/admin/organizations/_form.html.haml
= render 'admin/organizations/forms/fields', f: f, organization: organization

.content-box
  %h2 Contacts
  - if organization.contacts.present?
    Click a Contact below to view and update it:
    %p
    - organization.contacts.each do |contact|
      = link_to contact.name, edit_admin_organization_contact_path(organization, contact)
      %br
  %p
    = link_to t('admin.buttons.add_contact'), new_admin_organization_contact_path(organization), class: 'btn btn-primary'

.danger-zone
  %header
    %strong
      Danger Zone
  %h4
    Delete this organization
  %p
    Once you delete an organization, there is no going back. Please be certain.
  %p
    = link_to t('admin.buttons.delete_organization'), {}, href: '', data: { toggle: 'modal', target: '#modal-window' }, class: 'boxed-action'
.modal.fade#modal-window{ 'aria-hidden' => 'true', 'aria-labelledby' => 'my-modal-label', 'role' => 'dialog', 'tabindex' => '-1' }
  = render 'admin/organizations/confirm_delete_organization', org_id: organization.id, org_name: organization.name

.save-box.navbar-default
  %p
    Editing
    %strong
      = organization.name
  = f.submit t('admin.buttons.save_changes'), class: 'btn btn-success', data: { disable_with: 'Please wait...' }

app/views/admin/organizations/edit.html.haml
.content-box
  %h2= @organization.name
= form_for [:admin, @organization], html: { class: 'edit-entry' } do |f|
  = render 'admin/organizations/form', f: f, organization: @organization

app/views/admin/organizations/index.html.haml
%div.events-header
  %p Organizations
  = select(:organization, :approval_status, options_for_select([['Filter By Approval Status'], ['All', 'all'], ['Pending', 'pending'], ['Approved', 'approved'], ['Denied', 'denied']], disabled: 'Filter By Approval Status'), {}, { class: 'form-control' })
  = select(:organization, :is_published, options_for_select([['Filter By Published'], ['All', 'all'], ['Yes', 'true'], ['No', 'false']], disabled: 'Filter By Published'), {}, { class: 'form-control' })
%br
%br
%table{cellspacing: 30, class: 'custom-table'}
  %thead
    %tr
      %th Name
      %th Owner
      %th Approval Status
      %th Published?
  %tbody
    - @orgs.each do |organization|
      %tr
        %td= link_to organization[1], admin_organization_path(organization[2])
        %td= organization[3]
        %td= organization[4] || 'Pending'
        %td= organization[5].is_a?(FalseClass) ? 'No' : 'Yes'
%div.bottom-pagination
  = paginate @orgs

app/views/admin/organizations/new.html.haml
.content-box
  %h1 Create a new organization

= form_for [:admin, @organization], url: admin_organizations_path, html: { method: :post, class: 'edit-entry' } do |f|
  = render 'admin/organizations/forms/new_organization_form', f: f, organization: @organization

app/views/admin/organizations/show.html.haml
= form_for [:admin, @organization], html: { class: 'edit-entry' } do |f|
  %div.events-header
    %p
      %b= @organization.name
    = f.select(:approval_status, options_for_select([['Approval Status'], ['Pending', 'pending'], ['Approved', 'approved'], ['Denied', 'denied']], disabled: 'Approval Status', selected: @organization.approval_status), {}, { class: 'form-control', id: 'test-ds' })
  %br
  %p= @organization.description
  %br
  - if @organization.is_published
    %a{ href: "#{ENV.fetch('FRONT_ENV_APP_URL')}/businesses/#{@organization.id}", class: 'btn btn-primary btn-lg', target: '_blank' }
      View Organization
  =link_to 'Edit Organization', edit_admin_organization_path(@organization.slug), class: 'btn btn-primary btn-lg'
  .save-box.navbar-default
    = f.submit t('admin.buttons.save_changes_organization'), class: 'btn btn-success btn-lg', data: { disable_with: 'Please wait...' }